### ISSUE TITLE
Need some help with a manual installation

### ISSUE THREAD

**Issue by ovizii** [songchenwen/plexdlnaplayer#17]
So far I have only used this via the docker image, but I now need to run it on a Raspberry Pi zero where resources are scarce, so I tried manually:
```

git clone https://github.com/songchenwen/plexdlnaplayer.git
cd plexdlnaplayer
python3 main.py
```

yields this error:

```
python3 main.py 
Traceback (most recent call last):
  File "/home/ovi/plexdlnaplayer/main.py", line 1, in <module>
    from plex.plexserver import start_plex_server
  File "/home/ovi/plexdlnaplayer/plex/__init__.py", line 1, in <module>
    from .plexserver import plex_server
  File "/home/ovi/plexdlnaplayer/plex/plexserver.py", line 2, in <module>
    from fastapi import FastAPI, Request, Header, Query, HTTPException, Form
ModuleNotFoundError: No module named 'fastapi'
```

python3 is already the newest version (3.9.2-3)

Any ideas? I am now trying "pip install fastapi " but if I need additional modules should this not be mentioned somewhere?

**Comment by ovizii** [comment]
so I got it running after countless messages about missing modules, followed by `pip install "missing-module"` 

My last question now would be, how do I get it to autostart upon reboot?
