### ISSUE TITLE
Error: Unknown host 192-168-0-99.{PLEX_TOKEN}.plex.direct:32400

### ISSUE THREAD

**Issue by MattFromGer** [songchenwen/plexdlnaplayer#23]
When trying to cast (after linking the device), I get the errror 
`Cannot connect to host 192-168-0-99.PLEX_TOKEN.plex.direct:32400 ssl:default [nodename nor servname provided, or not known]`.
This is probably a configuration issue on my side?

```
INFO:     192.168.0.66:55746 - "GET /player/timeline/poll?wait=0&includeMetadata=1&commandID=5&type=music HTTP/1.1" 200 OK
get queue https://192-168-0-99.PLEX_TOKEN.plex.direct:32400/playQueues/5631?own=1&X-Plex-Token=transient-GUID1234
INFO:     192.168.0.66:55746 - "GET /player/playback/playMedia?source=SOURCE-GUID&containerKey=%2FplayQueues%2F5631%3Fown%3D1&key=%2Flibrary%2Fmetadata%2F21918&offset=25962&paused=1&token=transient-GUID1234&includeExternalMedia=1&type=music&protocol=https&address=192-168-0-99.PLEX_TOKEN.plex.direct&port=32400&machineIdentifier=MACHINE_ID&commandID=6 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/plex/plexserver.py", line 177, in play_media
    await adapter.play_media(containerKey, key=key, offset=offset, paused=paused, query_params=request.query_params)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/plex/adapters.py", line 393, in play_media
    await self.queue.get_info()
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/plex/play_queue.py", line 38, in get_info
    async with g.http.get(url, headers={"Accept": "application/json"}) as res:
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/mattfromger/PlexDlnaPlayerTest/plexdlnaplayer/.venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192-168-0-99.PLEX_TOKEN.plex.direct:32400 ssl:default [nodename nor servname provided, or not known]
```

**Comment by MattFromGer** [comment]
I finally fixed it. The URL is a `plex.direct` url that has to be resolved locally. The issue was my router (FritzBox) having "DNS Rebind Protection" enabled. I added `plex.direct` to the exclusions and finally the hostname is getting resolved correctly 👍
